version: "3.1"

services:
  kiss-worker:
    image: fishjar/kiss-worker
    # build: .
    environment:
      PORT: 8080
      APP_KEY: 123456
      APP_DATAPATH: data
    ports:
      - 8080:8080
    volumes:
      - ./data:/app/data
